Repository ClusterDuck-Protocol/ClusterDuck-Protocol, pull requests merged in 2024-03, with the labels that each got.

#354 Task/341 update board definitions
  .github/workflows/arduino_ci.yml
  examples/1.Ducks/DetectorDuck/platformio.ini
  examples/1.Ducks/DuckLink/DuckLink.ino
  examples/1.Ducks/DuckLink/platformio.ini
  examples/1.Ducks/MamaDuck/MamaDuck.ino
  examples/1.Ducks/MamaDuck/platformio.ini
  examples/1.Ducks/PapaDuck-Basic/PapaDuck-Basic.ino
  examples/1.Ducks/PapaDuck-Basic/platformio.ini
  examples/1.Ducks/PapaDuck/platformio.ini
  library.json
  library.properties
  platformio.ini
  src/CDP.h
  src/DuckLink.h
  src/DuckRadio.cpp
  src/MamaDuck.h
  src/PapaDuck.h
  src/bloomfilter.cpp
  src/include/boards/arduino_zero.h
  src/include/boards/cubecell_board.h
  src/include/boards/cubecell_gps.h
  src/include/boards/heltec_cubecell_board.h
  src/include/boards/heltec_cubecell_gps.h
  src/include/boards/heltec_wifi_lora_32_V2.h
  src/include/boards/heltec_wifi_lora_32_V3.h
  src/include/boards/heltec_wireless_stick.h
  src/include/boards/heltec_wireless_stick_lite.h
  src/include/boards/lilygo_t_beam_sx1262.h
  src/include/boards/lopy.h
  src/include/boards/lopy4.h
  src/include/boards/sparkfun_lora_gateway_1-channel.h
  src/include/boards/ttgo-lora32-v1.h
  src/include/boards/ttgo-lora32-v2.h
  src/include/boards/ttgo-lora32-v21.h
  src/include/boards/ttgo-t-beam.h
  src/include/boards/ttgo_t_beam_v1_sx1276.h
  src/include/cdpcfg.h
  src/setup_loop.cpp
  test/test_DuckPacket/test_DuckPacket.cpp
Labels: bug, software, high-priority

#370 License And Copyright Updater
  tools/license_updater.py
Labels: infrastructure

#373 Task/modular platformio ini
  platformio.ini
  src/config/cdp_common.ini
  src/config/cdp_common_test.ini
  src/config/cubecell_base.ini
  src/config/esp32_base.ini
  tools/cdp.py
Labels: maintenance, infrastructure

#364 Updated library.json to comply with platformio publishing
  library.json
Labels: infrastructure

#362 updated readme
  README.md
Labels: documentation, maintenance

#385 Hotfix doxygen file
  docs/Doxyfile
  src/include/cdpcfg.h
Labels: bug, documentation, infrastructure

#391 More readme updates
  README.md
  docs/assets/images/cdp_logo_white_bkg.png
Labels: documentation, maintenance

#389 Remove Python Arduino Dependency Install Script
  tools/cdp-dependency-automator-script/dependencies.json
  tools/cdp-dependency-automator-script/install-dependencies.py
  tools/cdp-dependency-automator-script/optional-dependencies.json
  tools/cdp-dependency-automator-script/requirements.txt
Labels: maintenance, infrastructure, pre-release

#390 Remove Chat and Message Board
  examples/1.Ducks/PapaDuck/PapaDuck.ino
  examples/5.Custom-Papa-Examples/PaPi-DMS-Lite-Examples/Serial-PaPiDuckExample/Serial-PaPiDuckExample.ino
  examples/5.Custom-Papa-Examples/Papa-DishDuck-WiFi/Papa-DishDuck-WiFi.ino
  examples/5.Custom-Papa-Examples/Papa-Downtime-Counter/Papa-Downtime-Counter.ino
  examples/7.Encryption/DecryptionPapaDuck/DecryptionPapaDuck.ino
  src/CdpPacket.h
  src/DuckNet.cpp
  src/DuckUtils.cpp
  src/Ducks/Duck.cpp
  src/Ducks/MamaDuck.cpp
  src/Ducks/PapaDuck.cpp
  src/PapaDuck.h
  src/circularBuffer.cpp
  src/include/Duck.h
  src/include/DuckNet.h
  src/include/DuckUtils.h
  src/include/cdpHome.h
  src/include/chatPage.h
  src/include/chatPrompt.h
  src/include/circularBuffer.h
  src/include/controlPanel.h
  src/include/messageBoard.h
  src/include/privateChat.h
  src/include/privateChatPrompt.h
  test/test_CircularBuffer/test_CircularBuffer.cpp
Labels: maintenance, pre-release

#398 395 end2end mini cluster example
  examples/2.Mini-Cluster/DuckLink/DuckLink.ino
  examples/2.Mini-Cluster/DuckLink/platformio.ini
  examples/2.Mini-Cluster/MamaDuck/MamaDuck.ino
  examples/2.Mini-Cluster/MamaDuck/platformio.ini
  examples/2.Mini-Cluster/PapaDuck-Mqtt/PapaDuck-Mqtt.ino
  examples/2.Mini-Cluster/PapaDuck-Mqtt/platformio.ini
  examples/2.Mini-Cluster/PapaDuck-Mqtt/web/app.js
  examples/2.Mini-Cluster/PapaDuck-Mqtt/web/index.html
  src/DuckNet.cpp
Labels: software, test/qa, pre-release

#404 403 cdp cli test command failure
  tools/CDP_CLI.md
  tools/cdp.py
Labels: bug

#413 Fixed issues in platformio for cubecell v2. Switch compiler to gnu++11
  platformio.ini
Labels: bug, infrastructure, pre-release
